week13/hackademy/education/urls.py
from django.urls import path, include

from education.views import index, courses, lectures

app_name = 'education'

courses_patterns = [
    path('', courses.list, name='list'),
    path('<int:course_id>/', courses.detail, name='detail'),
    path('new/', courses.CourseCreateView.as_view(), name='create'),
]

lectures_patterns = [
    path('', lectures.list, name='list'),
    path('<int:lecture_id>/', lectures.detail, name='detail'),
    path('new/', lectures.LectureCreateView.as_view(), name='create'),
]

urlpatterns = [
    path('', index, name='index'),
    path('courses/', include((courses_patterns, 'courses'))),
    path('lectures/', include((lectures_patterns, 'lectures'))),
]

week13/hackademy/hackademy/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('education/', include('education.urls')),
    path('admin/', admin.site.urls),
]

week13/hackademy/education/models.py
from django.db import models
from django.utils import timezone


class Course(models.Model):
    name = models.CharField(max_length=250, unique=True)
    description = models.TextField()
    start_date = models.DateTimeField(default=timezone.now)
    end_date = models.DateTimeField(null=True)

    def __str__(self):
        return f'Course "{self.name}"'

    @property
    def duration(self):
        if self.end_date:
            return self.end_date - self.start_date


class Lecture(models.Model):
    lecture_id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=250)
    week = models.CharField(max_length=10)
    course = models.ForeignKey(Course, on_delete=models.CASCADE, null=True)
    url = models.TextField()

    def __str__(self):
        return f'"{self.name}"'


class Task(models.Model):
    name = models.CharField(max_length=250, unique=True)
    description = models.TextField()
    due_date = models.DateTimeField(default=timezone.now)
    course = models.ForeignKey(Course, on_delete=models.CASCADE, null=True)
    lecture = models.ForeignKey(Lecture, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return f'Task "{self.name}"'


class Solution(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE, null=True)
    date = models.DateTimeField(default=timezone.now)
    url = models.TextField()

    def __str__(self):
        return f'Solution to Task {self.task}'

week13/hackademy/education/views.py
from django.shortcuts import render

# Create your views here.

week13/hackademy/education/views/courses.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import CreateView
from django.urls import reverse_lazy

from education.models import Course


def list(request):
    return render(request, 'courses/list.html', {'courses': Course.objects.all()})


def detail(request, course_id):
    course = get_object_or_404(Course, id=course_id)
    return render(request, 'courses/detail.html', {'course': course})


class CourseCreateView(CreateView):
    model = Course
    fields = ['name', 'description', 'start_date', 'end_date']
    template_name = 'courses/create.html'

    def get_success_url(self, **kwargs):
        return reverse_lazy('education:courses:detail', kwargs={'course_id': self.object.id})

week13/hackademy/education/views/lectures.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import CreateView
from django.urls import reverse_lazy

from education.models import Lecture


def list(request):
    return render(request, 'lectures/list.html', {'lectures': Lecture.objects.all()})


def detail(request, lecture_id):
    lecture = get_object_or_404(Lecture, id=lecture_id)
    return render(request, 'lectures/detail.html', {'lectures': lecture})


class LectureCreateView(CreateView):
    model = Lecture
    fields = ['name', 'week', 'course', 'url']
    template_name = 'lectures/create.html'

    def get_success_url(self, **kwargs):
        return reverse_lazy('education:lecture:detail', kwargs={'lecture_id': self.object.id})

week13/hackademy/education/templates/courses/base.html
<a href="{% url 'education:index' %}">Home</a>
<h1><a href="{% url 'education:courses:list' %}">Courses</a></h1>

{% block content %} {% endblock %}

week13/hackademy/education/templates/courses/create.html
<h2>Add new course</h2>

<form method="POST">
  {% csrf_token %} {{ form.as_p }}
  <input type="submit" name="Save" />
</form>

week13/hackademy/education/templates/courses/detail.html
{% extends "courses/base.html" %} {% block content %}
<h2>{{ course.name }}</h2>
{% endblock %}

week13/hackademy/education/templates/courses/list.html
{% extends "courses/base.html" %} {% block content %}
<a href="{% url 'education:courses:create' %}">Add new</a>


<html>
<head>
<style>
table, th, td {
  border: 1px solid black;
  border-collapse: collapse;
  padding: 10px;
}
</style>
</head>
<body>


{% if courses %}
<table style="background-color:#ffe6cc">
    <thead>
        <tr>
            <th>Course</th>
            <th>Description</th>
            <th>Start Date</th>
            <th>End Date</th>
            <th>Duration</th>
        </tr>
    </thead>
<ul>
  {% for course in courses %}
    <tr>
            <td><a href="{% url 'education:courses:detail' course.id %}">{{course.name}}</a></td>
            <td>{{course.description}}</td>
            <td>{{course.start_date}}</td>
            <td>{{course.end_date}}</td>
            <td>{{course.months_duration}} months</td>
    </tr>
  {% endfor %}
</ul>
</table>
{% else %}
<p><strong>No courses yet.</strong></p>
{% endif %} {% endblock %}

week13/hackademy/education/templates/index.html
<h1>Welcome to Hackademy!</h1>

<ul>
  <li><a href="{% url 'education:courses:list' %}">Courses</a></li>
  <li><a href="{% url 'education:lectures:list' %}">Lectures</a></li>
</ul>

week13/hackademy/education/templates/lectures/base.html
<a href="{% url 'education:index' %}">Home</a>
<h1><a href="{% url 'education:lectures:list' %}">Lectures</a></h1>

{% block content %} {% endblock %}

week13/hackademy/education/templates/lectures/create.html
<h3>Add new lecture</h3>

<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" name="Save" />
</form>

week13/hackademy/education/templates/lectures/detail.html
{% extends "lectures/base.html" %} {% block content %}
<h2>{{ lecture.name }}</h2>
{% endblock %}

week13/hackademy/education/templates/lectures/list.html
{% extends "lectures/base.html" %} {% block content %}
<a href="{% url 'education:lectures:create' %}">Add new</a>

<html>
<head>
<style>
table, th, td {
  border: 1px solid black;
  border-collapse: collapse;
  padding: 10px;
}

</style>
</head>
<body>



{% if lectures %}
<table style="background-color:#ffe6cc">
    <thead>
        <tr>
            <th>Lecture</th>
            <th>Week</th>
            <th>Course</th>
            <th>Url</th>
        </tr>
    </thead>
<ul>
    {% for lecture in lectures %}
    <tr>
        <td><a href="{% url 'education:lectures:detail' lecture.lecture_id %}">{{lecture.name}}</a></td>
        <td><a href="{% url 'education:lectures:detail' lecture.lecture_id %}">{{lecture.week}}</a></td>
        <td><a href="{% url 'education:lectures:detail' lecture.lecture_id %}">{{lecture.course}}</a></td>
        <td><a href="{% url 'education:lectures:detail' lecture.lecture_id %}">{{lecture.url}}</a></td>
    </tr>
    {% endfor %}
</ul>
</table>
{% else %}
<p><strong>No lectures yet.</strong></p>
{% endif %}
{% endblock %}